import { AppKitProvider } from '@/components/providers/wallet-connect';
import EndCTA from '@/components/shared/end-cta';
import Footer from '@/components/shared/footer';
import Header from '@/components/shared/header';
import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import { Geist_Mono, Sora } from 'next/font/google';

import './globals.css';

import { ThemeProvider } from '@/components/shared/theme-provider';

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const soraSans = Sora({
  variable: '--font-sora-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${soraSans.className} ${geistMono.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <AppKitProvider>
            <Header />
            {children}
            <EndCTA />
            <Footer />
          </AppKitProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
